[package]
name = "golf-peaks"
version = "0.1.0"
authors = ["Nicholas Whittaker <nicholas@nicholas.cloud>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
